services:
  hotmesh:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "9229:9229"
    environment:
      - NODE_ENV=development
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotmesh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]
    healthcheck:
      test: ["CMD", "nats", "ping", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
